# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  none

pool:
  #vmImage: ubuntu-latest
  name: pool1

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Docker@2
  inputs:
    containerRegistry: 'arc-cred'
    repository: 'pythonapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'fullaccessportal'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       echo "Deleting Docker image..."
#       az acr repository delete --name himani112  --repository pythonapp --tag $(Build.BuildId)-1 --yes